id: P008197
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15009
  title: སྟོད་ལུང་བདེ་ཆེན་རྫོང་གི་དཀར་ཆག
  author: ''
  volumes:
    f8365613487d4d95a5e409771e2ae5a9:
      image_group_id: I4PD4504
      title: ''
      volume_number: 1
      total_pages: 1138
      base_file: v001.txt
